name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
      if: steps.setup-go.outputs.go-version == '1.16' || steps.setup-go.outputs.go-version == '1.17'
    - name: Get dependencies (Go 1.15 and older)
      run: go mod download
      if: steps.setup-go.outputs.go-version != '1.16' && steps.setup-go.outputs.go-version != '1.17'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
