name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test on Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.15', '1.16', '1.17', '1.18', '1.19', '1.20', '1.21'  ]
      fail-fast: false # Опция позволяет продолжать другие сборки даже если одна из них неудачна.

    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Get dependencies (Go 1.16 and newer)
      run: go get -v -t -d ./...
      if: matrix.go_version == '1.16' || matrix.go_version == '1.17'
    
    - name: Get dependencies (Go 1.15 and older)
      run: go mod download
      if: matrix.go_version != '1.16' && matrix.go_version != '1.17'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
