name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build & Test on Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.16', '1.17', '1.18', '1.19', '1.20', '1.21'  ]
      fail-fast: false

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...
    
    - name: Test with Coverage
      run: |
        go test -v -coverpkg=./... -coverprofile=coverage.txt ./...
        go tool cover -func=coverage.txt
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.txt
        fail_ci_if_error: true